# Generated by Django 4.0 on 2022-01-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_createdtime_album_createdtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='feature',
            new_name='features',
        ),
    ]
